// Generated by tools/merge_packets.py from the DoomFlight and DoomCoprocessor dictionaries. Do not edit.

#ifndef DOOMSATELLITE_DOOMSATELLITEMERGEDPACKETS_HPP
#define DOOMSATELLITE_DOOMSATELLITEMERGEDPACKETS_HPP

#include "Svc/TlmPacketizer/TlmPacketizerTypes.hpp"

namespace DoomFlight {
namespace DoomSatelliteMergedPackets {

//! Number of packets in the merged packet list
constexpr FwChanIdType NUM_PACKETS = 58;

//! Number of distinct channels in the merged packet list
constexpr FwChanIdType NUM_CHANNELS = 98;

//! Merged DoomFlight and DoomCoprocessor packet list
extern const Svc::TlmPacketizerPacketList packetList;

}  // namespace DoomSatelliteMergedPackets
}  // namespace DoomFlight

#endif
