// Generated by tools/merge_packets.py from the DoomFlight and DoomCoprocessor dictionaries. Do not edit.

#include "DoomSatellite/DoomFlight/Top/DoomSatelliteMergedPackets.hpp"

#include "Fw/Time/Time.hpp"
#include "TlmPacketizerConfig/TlmPacketizerCfg.hpp"

namespace DoomFlight {
namespace DoomSatelliteMergedPackets {

static_assert(NUM_PACKETS <= Svc::MAX_PACKETIZER_PACKETS, "MAX_PACKETIZER_PACKETS too small for merged packets");
static_assert(NUM_CHANNELS <= Svc::MAX_PACKETIZER_CHANNELS, "MAX_PACKETIZER_CHANNELS too small for merged packets");

namespace {

//! Packet header: descriptor, packet id, and time tag
constexpr FwSizeType PACKET_HEADER_SIZE =
    sizeof(FwPacketDescriptorType) + sizeof(FwTlmPacketizeIdType) + Fw::Time::SERIALIZED_SIZE;

// Packet Health: id 0x1, group 1, 32 data bytes
constexpr Svc::TlmPacketizerChannelEntry HealthChannels[] = {
    {0x01000000, 4},  // CdhCore.cmdDisp.CommandsDispatched
    {0x01000002, 4},  // CdhCore.cmdDisp.CommandsDropped
    {0x02000000, 8},  // ComCcsds.comQueue.comQueueDepth
    {0x02002002, 4},  // ComCcsds.commsBufferManager.HiBuffs
    {0x1001a002, 4},  // DoomFlight.hubBufferManager.HiBuffs
    {0x10001000, 4},  // DoomFlight.rateGroup10Hz.RgMaxTime
    {0x10002000, 4},  // DoomFlight.rateGroup1Hz.RgMaxTime
};
static_assert(PACKET_HEADER_SIZE + 32 <= FW_COM_BUFFER_MAX_SIZE, "Packet Health exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket Health = {HealthChannels, 0x1, 1, FW_NUM_ARRAY_ELEMENTS(HealthChannels)};

// Packet HealthWarnings: id 0x2, group 1, 36 data bytes
constexpr Svc::TlmPacketizerChannelEntry HealthWarningsChannels[] = {
    {0x01002000, 4},  // CdhCore.health.PingLateWarnings
    {0x01001000, 8},  // CdhCore.events.EventsDropped
    {0x02002003, 4},  // ComCcsds.commsBufferManager.NoBuffs
    {0x02002004, 4},  // ComCcsds.commsBufferManager.EmptyBuffs
    {0x1001a003, 4},  // DoomFlight.hubBufferManager.NoBuffs
    {0x1001a004, 4},  // DoomFlight.hubBufferManager.EmptyBuffs
    {0x10001001, 4},  // DoomFlight.rateGroup10Hz.RgCycleSlips
    {0x10002001, 4},  // DoomFlight.rateGroup1Hz.RgCycleSlips
};
static_assert(PACKET_HEADER_SIZE + 36 <= FW_COM_BUFFER_MAX_SIZE, "Packet HealthWarnings exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket HealthWarnings = {HealthWarningsChannels, 0x2, 1, FW_NUM_ARRAY_ELEMENTS(HealthWarningsChannels)};

// Packet HealthAuxillary: id 0x3, group 2, 77 data bytes
constexpr Svc::TlmPacketizerChannelEntry HealthAuxillaryChannels[] = {
    {0x02002000, 4},  // ComCcsds.commsBufferManager.TotalBuffs
    {0x02002001, 4},  // ComCcsds.commsBufferManager.CurrBuffs
    {0x02000001, 4},  // ComCcsds.comQueue.buffQueueDepth
    {0x1001a000, 4},  // DoomFlight.hubBufferManager.TotalBuffs
    {0x1001a001, 4},  // DoomFlight.hubBufferManager.CurrBuffs
    {0x01006000, 56},  // CdhCore.tlmSend.GroupConfigs
    {0x01006001, 1},  // CdhCore.tlmSend.SectionEnabled
};
static_assert(PACKET_HEADER_SIZE + 77 <= FW_COM_BUFFER_MAX_SIZE, "Packet HealthAuxillary exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket HealthAuxillary = {HealthAuxillaryChannels, 0x3, 2, FW_NUM_ARRAY_ELEMENTS(HealthAuxillaryChannels)};

// Packet Version: id 0x4, group 3, 192 data bytes
constexpr Svc::TlmPacketizerChannelEntry VersionChannels[] = {
    {0x01003000, 48},  // CdhCore.version.FrameworkVersion
    {0x01003001, 48},  // CdhCore.version.ProjectVersion
    {0x0100300c, 48},  // CdhCore.version.LibraryVersion01
    {0x0100300d, 48},  // CdhCore.version.LibraryVersion02
};
static_assert(PACKET_HEADER_SIZE + 192 <= FW_COM_BUFFER_MAX_SIZE, "Packet Version exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket Version = {VersionChannels, 0x4, 3, FW_NUM_ARRAY_ELEMENTS(VersionChannels)};

// Packet FlightFrameAdapter: id 0x10, group 1, 20 data bytes
constexpr Svc::TlmPacketizerChannelEntry FlightFrameAdapterChannels[] = {
    {0x1001d000, 4},  // DoomFlight.frameAdapter.PackedRejected
    {0x1001d002, 4},  // DoomFlight.frameAdapter.FramesUnpacked
    {0x1001d003, 4},  // DoomFlight.frameAdapter.FramesRejected
    {0x1001d005, 4},  // DoomFlight.frameAdapter.PalettesUnpacked
    {0x1001d006, 4},  // DoomFlight.frameAdapter.PalettesRejected
};
static_assert(PACKET_HEADER_SIZE + 20 <= FW_COM_BUFFER_MAX_SIZE, "Packet FlightFrameAdapter exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket FlightFrameAdapter = {FlightFrameAdapterChannels, 0x10, 1, FW_NUM_ARRAY_ELEMENTS(FlightFrameAdapterChannels)};

// Packet DoomEngine: id 0x100, group 1, 37 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomEngineChannels[] = {
    {0x2d000052, 4},  // DoomSubtopology.doom.State
    {0x2d000050, 8},  // DoomSubtopology.doom.FrameCount
    {0x2d000053, 1},  // DoomSubtopology.doom.KeyQueueDepth
    {0x2d000054, 4},  // DoomSubtopology.doom.KeyEventsDropped
    {0x2d000055, 4},  // DoomSubtopology.doom.FramesDropped
    {0x2d000056, 4},  // DoomSubtopology.doom.FrameRateHz
    {0x2d000057, 4},  // DoomSubtopology.doom.FrameDataRateBps
    {0x2d000059, 4},  // DoomSubtopology.doom.InputCommandRateHz
    {0x2d000058, 4},  // DoomSubtopology.doom.InputDataRateBps
};
static_assert(PACKET_HEADER_SIZE + 37 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomEngine exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomEngine = {DoomEngineChannels, 0x100, 1, FW_NUM_ARRAY_ELEMENTS(DoomEngineChannels)};

// Packet DoomPalette: id 0x101, group 1, 772 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomPaletteChannels[] = {
    {0x2d003190, 772},  // DoomFlight.frameTlmProcessor.PaletteOut
};
static_assert(PACKET_HEADER_SIZE + 772 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomPalette exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomPalette = {DoomPaletteChannels, 0x101, 1, FW_NUM_ARRAY_ELEMENTS(DoomPaletteChannels)};

// Packet CoprocessorFrameAdapter: id 0x102, group 1, 28 data bytes
constexpr Svc::TlmPacketizerChannelEntry CoprocessorFrameAdapterChannels[] = {
    {0x2000a000, 4},  // DoomCoprocessor.frameAdapter.PackedRejected
    {0x2000a001, 4},  // DoomCoprocessor.frameAdapter.FramesPacked
    {0x2000a002, 4},  // DoomCoprocessor.frameAdapter.FramesUnpacked
    {0x2000a003, 4},  // DoomCoprocessor.frameAdapter.FramesRejected
    {0x2000a004, 4},  // DoomCoprocessor.frameAdapter.PalettesPacked
    {0x2000a005, 4},  // DoomCoprocessor.frameAdapter.PalettesUnpacked
    {0x2000a006, 4},  // DoomCoprocessor.frameAdapter.PalettesRejected
};
static_assert(PACKET_HEADER_SIZE + 28 <= FW_COM_BUFFER_MAX_SIZE, "Packet CoprocessorFrameAdapter exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket CoprocessorFrameAdapter = {CoprocessorFrameAdapterChannels, 0x102, 1, FW_NUM_ARRAY_ELEMENTS(CoprocessorFrameAdapterChannels)};

// Packet DoomFrameRow000: id 0x200, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow000Channels[] = {
    {0x2d003000, 88},  // DoomFlight.frameTlmProcessor.FrameRow000
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow000 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow000 = {DoomFrameRow000Channels, 0x200, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow000Channels)};

// Packet DoomFrameRow001: id 0x201, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow001Channels[] = {
    {0x2d003001, 88},  // DoomFlight.frameTlmProcessor.FrameRow001
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow001 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow001 = {DoomFrameRow001Channels, 0x201, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow001Channels)};

// Packet DoomFrameRow002: id 0x202, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow002Channels[] = {
    {0x2d003002, 88},  // DoomFlight.frameTlmProcessor.FrameRow002
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow002 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow002 = {DoomFrameRow002Channels, 0x202, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow002Channels)};

// Packet DoomFrameRow003: id 0x203, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow003Channels[] = {
    {0x2d003003, 88},  // DoomFlight.frameTlmProcessor.FrameRow003
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow003 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow003 = {DoomFrameRow003Channels, 0x203, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow003Channels)};

// Packet DoomFrameRow004: id 0x204, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow004Channels[] = {
    {0x2d003004, 88},  // DoomFlight.frameTlmProcessor.FrameRow004
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow004 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow004 = {DoomFrameRow004Channels, 0x204, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow004Channels)};

// Packet DoomFrameRow005: id 0x205, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow005Channels[] = {
    {0x2d003005, 88},  // DoomFlight.frameTlmProcessor.FrameRow005
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow005 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow005 = {DoomFrameRow005Channels, 0x205, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow005Channels)};

// Packet DoomFrameRow006: id 0x206, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow006Channels[] = {
    {0x2d003006, 88},  // DoomFlight.frameTlmProcessor.FrameRow006
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow006 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow006 = {DoomFrameRow006Channels, 0x206, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow006Channels)};

// Packet DoomFrameRow007: id 0x207, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow007Channels[] = {
    {0x2d003007, 88},  // DoomFlight.frameTlmProcessor.FrameRow007
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow007 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow007 = {DoomFrameRow007Channels, 0x207, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow007Channels)};

// Packet DoomFrameRow008: id 0x208, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow008Channels[] = {
    {0x2d003008, 88},  // DoomFlight.frameTlmProcessor.FrameRow008
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow008 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow008 = {DoomFrameRow008Channels, 0x208, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow008Channels)};

// Packet DoomFrameRow009: id 0x209, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow009Channels[] = {
    {0x2d003009, 88},  // DoomFlight.frameTlmProcessor.FrameRow009
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow009 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow009 = {DoomFrameRow009Channels, 0x209, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow009Channels)};

// Packet DoomFrameRow010: id 0x20a, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow010Channels[] = {
    {0x2d00300a, 88},  // DoomFlight.frameTlmProcessor.FrameRow010
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow010 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow010 = {DoomFrameRow010Channels, 0x20a, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow010Channels)};

// Packet DoomFrameRow011: id 0x20b, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow011Channels[] = {
    {0x2d00300b, 88},  // DoomFlight.frameTlmProcessor.FrameRow011
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow011 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow011 = {DoomFrameRow011Channels, 0x20b, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow011Channels)};

// Packet DoomFrameRow012: id 0x20c, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow012Channels[] = {
    {0x2d00300c, 88},  // DoomFlight.frameTlmProcessor.FrameRow012
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow012 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow012 = {DoomFrameRow012Channels, 0x20c, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow012Channels)};

// Packet DoomFrameRow013: id 0x20d, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow013Channels[] = {
    {0x2d00300d, 88},  // DoomFlight.frameTlmProcessor.FrameRow013
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow013 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow013 = {DoomFrameRow013Channels, 0x20d, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow013Channels)};

// Packet DoomFrameRow014: id 0x20e, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow014Channels[] = {
    {0x2d00300e, 88},  // DoomFlight.frameTlmProcessor.FrameRow014
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow014 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow014 = {DoomFrameRow014Channels, 0x20e, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow014Channels)};

// Packet DoomFrameRow015: id 0x20f, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow015Channels[] = {
    {0x2d00300f, 88},  // DoomFlight.frameTlmProcessor.FrameRow015
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow015 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow015 = {DoomFrameRow015Channels, 0x20f, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow015Channels)};

// Packet DoomFrameRow016: id 0x210, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow016Channels[] = {
    {0x2d003010, 88},  // DoomFlight.frameTlmProcessor.FrameRow016
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow016 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow016 = {DoomFrameRow016Channels, 0x210, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow016Channels)};

// Packet DoomFrameRow017: id 0x211, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow017Channels[] = {
    {0x2d003011, 88},  // DoomFlight.frameTlmProcessor.FrameRow017
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow017 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow017 = {DoomFrameRow017Channels, 0x211, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow017Channels)};

// Packet DoomFrameRow018: id 0x212, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow018Channels[] = {
    {0x2d003012, 88},  // DoomFlight.frameTlmProcessor.FrameRow018
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow018 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow018 = {DoomFrameRow018Channels, 0x212, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow018Channels)};

// Packet DoomFrameRow019: id 0x213, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow019Channels[] = {
    {0x2d003013, 88},  // DoomFlight.frameTlmProcessor.FrameRow019
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow019 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow019 = {DoomFrameRow019Channels, 0x213, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow019Channels)};

// Packet DoomFrameRow020: id 0x214, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow020Channels[] = {
    {0x2d003014, 88},  // DoomFlight.frameTlmProcessor.FrameRow020
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow020 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow020 = {DoomFrameRow020Channels, 0x214, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow020Channels)};

// Packet DoomFrameRow021: id 0x215, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow021Channels[] = {
    {0x2d003015, 88},  // DoomFlight.frameTlmProcessor.FrameRow021
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow021 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow021 = {DoomFrameRow021Channels, 0x215, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow021Channels)};

// Packet DoomFrameRow022: id 0x216, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow022Channels[] = {
    {0x2d003016, 88},  // DoomFlight.frameTlmProcessor.FrameRow022
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow022 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow022 = {DoomFrameRow022Channels, 0x216, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow022Channels)};

// Packet DoomFrameRow023: id 0x217, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow023Channels[] = {
    {0x2d003017, 88},  // DoomFlight.frameTlmProcessor.FrameRow023
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow023 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow023 = {DoomFrameRow023Channels, 0x217, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow023Channels)};

// Packet DoomFrameRow024: id 0x218, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow024Channels[] = {
    {0x2d003018, 88},  // DoomFlight.frameTlmProcessor.FrameRow024
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow024 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow024 = {DoomFrameRow024Channels, 0x218, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow024Channels)};

// Packet DoomFrameRow025: id 0x219, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow025Channels[] = {
    {0x2d003019, 88},  // DoomFlight.frameTlmProcessor.FrameRow025
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow025 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow025 = {DoomFrameRow025Channels, 0x219, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow025Channels)};

// Packet DoomFrameRow026: id 0x21a, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow026Channels[] = {
    {0x2d00301a, 88},  // DoomFlight.frameTlmProcessor.FrameRow026
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow026 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow026 = {DoomFrameRow026Channels, 0x21a, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow026Channels)};

// Packet DoomFrameRow027: id 0x21b, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow027Channels[] = {
    {0x2d00301b, 88},  // DoomFlight.frameTlmProcessor.FrameRow027
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow027 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow027 = {DoomFrameRow027Channels, 0x21b, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow027Channels)};

// Packet DoomFrameRow028: id 0x21c, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow028Channels[] = {
    {0x2d00301c, 88},  // DoomFlight.frameTlmProcessor.FrameRow028
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow028 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow028 = {DoomFrameRow028Channels, 0x21c, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow028Channels)};

// Packet DoomFrameRow029: id 0x21d, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow029Channels[] = {
    {0x2d00301d, 88},  // DoomFlight.frameTlmProcessor.FrameRow029
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow029 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow029 = {DoomFrameRow029Channels, 0x21d, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow029Channels)};

// Packet DoomFrameRow030: id 0x21e, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow030Channels[] = {
    {0x2d00301e, 88},  // DoomFlight.frameTlmProcessor.FrameRow030
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow030 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow030 = {DoomFrameRow030Channels, 0x21e, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow030Channels)};

// Packet DoomFrameRow031: id 0x21f, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow031Channels[] = {
    {0x2d00301f, 88},  // DoomFlight.frameTlmProcessor.FrameRow031
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow031 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow031 = {DoomFrameRow031Channels, 0x21f, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow031Channels)};

// Packet DoomFrameRow032: id 0x220, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow032Channels[] = {
    {0x2d003020, 88},  // DoomFlight.frameTlmProcessor.FrameRow032
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow032 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow032 = {DoomFrameRow032Channels, 0x220, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow032Channels)};

// Packet DoomFrameRow033: id 0x221, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow033Channels[] = {
    {0x2d003021, 88},  // DoomFlight.frameTlmProcessor.FrameRow033
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow033 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow033 = {DoomFrameRow033Channels, 0x221, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow033Channels)};

// Packet DoomFrameRow034: id 0x222, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow034Channels[] = {
    {0x2d003022, 88},  // DoomFlight.frameTlmProcessor.FrameRow034
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow034 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow034 = {DoomFrameRow034Channels, 0x222, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow034Channels)};

// Packet DoomFrameRow035: id 0x223, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow035Channels[] = {
    {0x2d003023, 88},  // DoomFlight.frameTlmProcessor.FrameRow035
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow035 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow035 = {DoomFrameRow035Channels, 0x223, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow035Channels)};

// Packet DoomFrameRow036: id 0x224, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow036Channels[] = {
    {0x2d003024, 88},  // DoomFlight.frameTlmProcessor.FrameRow036
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow036 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow036 = {DoomFrameRow036Channels, 0x224, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow036Channels)};

// Packet DoomFrameRow037: id 0x225, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow037Channels[] = {
    {0x2d003025, 88},  // DoomFlight.frameTlmProcessor.FrameRow037
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow037 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow037 = {DoomFrameRow037Channels, 0x225, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow037Channels)};

// Packet DoomFrameRow038: id 0x226, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow038Channels[] = {
    {0x2d003026, 88},  // DoomFlight.frameTlmProcessor.FrameRow038
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow038 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow038 = {DoomFrameRow038Channels, 0x226, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow038Channels)};

// Packet DoomFrameRow039: id 0x227, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow039Channels[] = {
    {0x2d003027, 88},  // DoomFlight.frameTlmProcessor.FrameRow039
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow039 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow039 = {DoomFrameRow039Channels, 0x227, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow039Channels)};

// Packet DoomFrameRow040: id 0x228, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow040Channels[] = {
    {0x2d003028, 88},  // DoomFlight.frameTlmProcessor.FrameRow040
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow040 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow040 = {DoomFrameRow040Channels, 0x228, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow040Channels)};

// Packet DoomFrameRow041: id 0x229, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow041Channels[] = {
    {0x2d003029, 88},  // DoomFlight.frameTlmProcessor.FrameRow041
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow041 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow041 = {DoomFrameRow041Channels, 0x229, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow041Channels)};

// Packet DoomFrameRow042: id 0x22a, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow042Channels[] = {
    {0x2d00302a, 88},  // DoomFlight.frameTlmProcessor.FrameRow042
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow042 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow042 = {DoomFrameRow042Channels, 0x22a, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow042Channels)};

// Packet DoomFrameRow043: id 0x22b, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow043Channels[] = {
    {0x2d00302b, 88},  // DoomFlight.frameTlmProcessor.FrameRow043
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow043 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow043 = {DoomFrameRow043Channels, 0x22b, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow043Channels)};

// Packet DoomFrameRow044: id 0x22c, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow044Channels[] = {
    {0x2d00302c, 88},  // DoomFlight.frameTlmProcessor.FrameRow044
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow044 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow044 = {DoomFrameRow044Channels, 0x22c, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow044Channels)};

// Packet DoomFrameRow045: id 0x22d, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow045Channels[] = {
    {0x2d00302d, 88},  // DoomFlight.frameTlmProcessor.FrameRow045
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow045 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow045 = {DoomFrameRow045Channels, 0x22d, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow045Channels)};

// Packet DoomFrameRow046: id 0x22e, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow046Channels[] = {
    {0x2d00302e, 88},  // DoomFlight.frameTlmProcessor.FrameRow046
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow046 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow046 = {DoomFrameRow046Channels, 0x22e, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow046Channels)};

// Packet DoomFrameRow047: id 0x22f, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow047Channels[] = {
    {0x2d00302f, 88},  // DoomFlight.frameTlmProcessor.FrameRow047
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow047 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow047 = {DoomFrameRow047Channels, 0x22f, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow047Channels)};

// Packet DoomFrameRow048: id 0x230, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow048Channels[] = {
    {0x2d003030, 88},  // DoomFlight.frameTlmProcessor.FrameRow048
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow048 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow048 = {DoomFrameRow048Channels, 0x230, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow048Channels)};

// Packet DoomFrameRow049: id 0x231, group 1, 88 data bytes
constexpr Svc::TlmPacketizerChannelEntry DoomFrameRow049Channels[] = {
    {0x2d003031, 88},  // DoomFlight.frameTlmProcessor.FrameRow049
};
static_assert(PACKET_HEADER_SIZE + 88 <= FW_COM_BUFFER_MAX_SIZE, "Packet DoomFrameRow049 exceeds FW_COM_BUFFER_MAX_SIZE");
constexpr Svc::TlmPacketizerPacket DoomFrameRow049 = {DoomFrameRow049Channels, 0x231, 1, FW_NUM_ARRAY_ELEMENTS(DoomFrameRow049Channels)};

}  // namespace

const Svc::TlmPacketizerPacketList packetList = {
    {
        &Health,
        &HealthWarnings,
        &HealthAuxillary,
        &Version,
        &FlightFrameAdapter,
        &DoomEngine,
        &DoomPalette,
        &CoprocessorFrameAdapter,
        &DoomFrameRow000,
        &DoomFrameRow001,
        &DoomFrameRow002,
        &DoomFrameRow003,
        &DoomFrameRow004,
        &DoomFrameRow005,
        &DoomFrameRow006,
        &DoomFrameRow007,
        &DoomFrameRow008,
        &DoomFrameRow009,
        &DoomFrameRow010,
        &DoomFrameRow011,
        &DoomFrameRow012,
        &DoomFrameRow013,
        &DoomFrameRow014,
        &DoomFrameRow015,
        &DoomFrameRow016,
        &DoomFrameRow017,
        &DoomFrameRow018,
        &DoomFrameRow019,
        &DoomFrameRow020,
        &DoomFrameRow021,
        &DoomFrameRow022,
        &DoomFrameRow023,
        &DoomFrameRow024,
        &DoomFrameRow025,
        &DoomFrameRow026,
        &DoomFrameRow027,
        &DoomFrameRow028,
        &DoomFrameRow029,
        &DoomFrameRow030,
        &DoomFrameRow031,
        &DoomFrameRow032,
        &DoomFrameRow033,
        &DoomFrameRow034,
        &DoomFrameRow035,
        &DoomFrameRow036,
        &DoomFrameRow037,
        &DoomFrameRow038,
        &DoomFrameRow039,
        &DoomFrameRow040,
        &DoomFrameRow041,
        &DoomFrameRow042,
        &DoomFrameRow043,
        &DoomFrameRow044,
        &DoomFrameRow045,
        &DoomFrameRow046,
        &DoomFrameRow047,
        &DoomFrameRow048,
        &DoomFrameRow049,
    },
    NUM_PACKETS};

}  // namespace DoomSatelliteMergedPackets
}  // namespace DoomFlight
